
/**
 * Backend Templates and Schema (Supabase Edition)
 * Use this reference for Supabase SQL Editor.
 */

/* 
  ===========================================
  SUPABASE DATABASE SCHEMA (SQL)
  ===========================================
  Run this in the Supabase SQL Editor to set up tables and security.
*/
export const DB_SCHEMA_SQL = `
-- 1. Profiles Table (Extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  first_name text,
  last_name text,
  email text,
  phone text,
  role text default 'athlete',
  subscription_tier text default 'free',
  subscription_status text default 'inactive',
  subscription_expiry timestamptz,
  is_banned boolean default false,
  admin_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, first_name, last_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', coalesce(new.raw_user_meta_data->>'role', 'athlete'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Payments Table
create table payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  user_name text,
  plan text,
  amount_usd numeric,
  method text,
  tx_id text,
  receipt_url text,
  months_paid int default 1,
  status text default 'pending', -- pending, waiting, needs_review, succeeded, failed
  created_at timestamptz default now()
);

alter table payments enable row level security;

-- Policies for Payments
create policy "Users can view own payments" on payments for select using (auth.uid() = user_id);
create policy "Users can insert payments" on payments for insert with check (auth.uid() = user_id);
create policy "Admins can view all payments" on payments for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
create policy "Admins can update payments" on payments for update using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- 3. Audit Logs
create table audit_logs (
  id bigint generated by default as identity primary key,
  admin text,
  action text,
  target text,
  created_at timestamptz default now()
);

alter table audit_logs enable row level security;
create policy "Admins can view audit logs" on audit_logs for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
create policy "Admins can insert audit logs" on audit_logs for insert with check (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- 4. Subscription Videos (NEW)
create table videos (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  category text,
  thumbnail_url text,
  video_url text not null,
  visibility text default 'free', -- free, members, vip
  views int default 0,
  created_at timestamptz default now()
);
alter table videos enable row level security;
create policy "Anyone can view free videos" on videos for select using (visibility = 'free');
create policy "Members can view member videos" on videos for select using (
  visibility = 'members' AND exists (select 1 from profiles where id = auth.uid() and subscription_status = 'active')
);
create policy "VIPs can view vip videos" on videos for select using (
  visibility = 'vip' AND exists (select 1 from profiles where id = auth.uid() and subscription_tier = 'elite_plus')
);
create policy "Admins manage videos" on videos for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- 5. User Activity (NEW)
create table user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  event_type text, -- login, page_view, video_watch, workout_open
  event_data jsonb,
  ip_address text,
  device_info text,
  timestamp timestamptz default now()
);
alter table user_activity enable row level security;
create policy "Users insert own activity" on user_activity for insert with check (auth.uid() = user_id);
create policy "Admins view activity" on user_activity for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- 6. Messages (NEW)
create table messages (
  id uuid default gen_random_uuid() primary key,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users, -- null for broadcast
  subject text,
  message text not null,
  is_read boolean default false,
  is_broadcast boolean default false,
  created_at timestamptz default now()
);
alter table messages enable row level security;
create policy "Users see own messages" on messages for select using (auth.uid() = receiver_id OR auth.uid() = sender_id OR is_broadcast = true);
create policy "Users send to admin" on messages for insert with check (
  receiver_id IN (select id from profiles where role = 'admin')
);
create policy "Admins send to all" on messages for insert with check (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
create policy "Admins view all" on messages for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- 7. Transactions Log (Advanced Financials - Optional Extension)
create table transactions_log (
  id uuid default gen_random_uuid() primary key,
  txid text,
  amount numeric,
  currency text default 'USDT',
  status text,
  confirmed_by_admin text,
  notes text,
  created_at timestamptz default now()
);
alter table transactions_log enable row level security;
create policy "Admins manage tx logs" on transactions_log for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- 8. Athlete Activity (Consolidated Data for Analytics Export)
create table athlete_activity (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  date date not null,
  steps int default 0,
  calories int default 0,
  workout_minutes int default 0,
  distance_km float default 0,
  water_ml int default 0,
  sleep_hours float default 0,
  weight float,
  body_fat float,
  created_at timestamptz default now()
);
alter table athlete_activity enable row level security;
create policy "Users manage own activity" on athlete_activity for all using (auth.uid() = user_id);

-- 9. Report Links (Sharing)
create table athlete_report_links (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  report_type text,  -- daily, weekly, monthly, yearly
  period_start date,
  period_end date,
  public_url text,
  passcode text,      -- optional for private links
  views int default 0,
  expires_at timestamptz,
  created_at timestamptz default now()
);
alter table athlete_report_links enable row level security;
create policy "Users manage own links" on athlete_report_links for all using (auth.uid() = user_id);
create policy "Public access to links" on athlete_report_links for select using (true);
`;

/* 
  ===========================================
  VERCEL SERVERLESS FUNCTION: Verify Tether
  ===========================================
*/
export const VERCEL_FUNCTION_VERIFY_USDT = `
import { createClient } from '@supabase/supabase-js';
import type { VercelRequest, VercelResponse } from '@vercel/node';
import axios from 'axios';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const TRONGRID_API_BASE = 'https://api.trongrid.io';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method Not Allowed' });

  const { txid, expectedAmount } = req.body;
  if (!txid) return res.status(400).json({ error: 'txid required' });

  try {
    const txResp = await axios.post(
      \`\${TRONGRID_API_BASE}/wallet/gettransactionbyid\`, 
      { value: txid },
      { headers: { 'TRON-PRO-API-KEY': process.env.TRONGRID_API_KEY || '' } }
    );

    const tx = txResp.data;
    if (!tx || !tx.ret || tx.ret[0].contractRet !== 'SUCCESS') {
      return res.json({ verified: false, message: 'Transaction not found or failed' });
    }

    await supabase.from('audit_logs').insert({
      admin: 'System',
      action: 'Verify TX',
      target: txid
    });

    return res.json({ verified: true, message: 'Transaction verified' });
  } catch (error: any) {
    console.error(error);
    return res.status(500).json({ error: 'Verification failed', detail: error.message });
  }
}
`;
